name: tasks_api
description: The interface and models for an API providing access to tasks.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  meta: ^1.9.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.23.1
  very_good_analysis: ^4.0.0+1